SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;

BEGIN;
	DROP TABLE IF EXISTS propUseLookup CASCADE;
	CREATE TABLE propUseLookup(
		 code varchar PRIMARY KEY,
		 descr varchar
	);
COMMIT;
	