.\Convert-fixedwidth-to-csv.ps1 -fwfile '..\valuedata\REC10_TRIM2013\*.TXT' -formatfile '.\formatfiles\REC10.csv'
.\Convert-fixedwidth-to-csv.ps1 -fwfile '..\valuedata\REC20_TRIM2013\*.TXT' -formatfile '.\formatfiles\REC20.csv'
.\Convert-fixedwidth-to-csv.ps1 -fwfile '..\valuedata\REC35_TRIM2013\*.TXT' -formatfile '.\formatfiles\REC35.csv'
.\Convert-fixedwidth-to-csv.ps1 -fwfile '..\valuedata\REC36_TRIM2013\*.TXT' -formatfile '.\formatfiles\REC36.csv'
.\Convert-fixedwidth-to-csv.ps1 -fwfile '..\valuedata\REC40_TRIM2013\*.TXT' -formatfile '.\formatfiles\REC40.csv'